### ISSUE TITLE
Some pages are inaccessible to users when logged in

### ISSUE THREAD

**Issue by korzq** [neptune-networks/feedback#22]
When logged in, user can not see more information about other services, like pricing, location, etc. 

![here is a picture](https://sc.ericz.dev/f4a5c3.png)

**Comment by bswinnerton** [comment]
Thanks for the report, @korzq 🙇‍♂️. I've went ahead and added back the navigation elements that weren't present for users who are feature flagged into the platform:

<img width="517" alt="Screen Shot 2020-05-18 at 9 37 35 PM" src="https://user-images.githubusercontent.com/934497/82275105-e57f1b00-994f-11ea-821f-766a31dca791.png">
