### ISSUE TITLE
Ability to specify the shutdown type

### ISSUE THREAD

**Issue by natesales** [neptune-networks/feedback#25]
It would be nice to have the ability to trigger both soft and forceful restarts.

**Comment by aredan** [comment]
A question asking for confirmation after clicking the Shut Off button will be great!

**Comment by bswinnerton** [comment]
Thanks y'all, I agree the current behavior is a bad user experience. I'll work on a solution to choose which type of shutdown next weekend.

**Comment by bswinnerton** [comment]
Shipping out a fix for this as we speak. Now when you click the shut down slider a modal appears asking what type of shutdown you would like:

<img width="1262" alt="84607519-c5be1280-ae7b-11ea-9b2d-3ca3e5646e55" src="https://user-images.githubusercontent.com/934497/84608242-77ab0e00-ae7f-11ea-8fbb-090661b15806.png">
