### ISSUE TITLE
Ability to select an empty option in transit VM selection

### ISSUE THREAD

**Issue by natesales** [neptune-networks/feedback#26]
It's possible to select an empty VM in the transit config page.

![image](https://user-images.githubusercontent.com/20391440/82270625-3d0a9000-992a-11ea-91cb-9ef14d2ce6a3.png)

**Comment by natesales** [comment]
It does check if the VM exists, but for simplicity it would be nice not to show an empty option at all.

![image](https://user-images.githubusercontent.com/20391440/82270649-50b5f680-992a-11ea-9d07-a5fcd639cae2.png)

**Comment by bswinnerton** [comment]
Good point, thanks for the issue @natesales. I went ahead and added a placeholder that removes itself once an option has been saved:

<img width="450" alt="Screen Shot 2020-05-18 at 9 37 21 PM" src="https://user-images.githubusercontent.com/934497/82275158-03e51680-9950-11ea-9da7-919dffcdf6c9.png">
