### ISSUE TITLE
UI Bug: OS selections resets on error

### ISSUE THREAD

**Issue by schiederme** [neptune-networks/feedback#38]
**Describe the bug**
If you try to order a Virtual Machine and forget to set the name, the OS selection resets to CentOS

**To Reproduce**
1. Go to 'Virtual Machines'
2. Click on 'Create Virtual Machine'
3. Don't insert a Name
4. Select a OS other then 'CentOS' e.g. 'Debian'
5. Click on 'Create'
6. See error

**Expected behavior**
The OS selection should stay the same e.g. not reset to CentOS

**Screenshots**
![2020-08-31 16 08 27](https://user-images.githubusercontent.com/30325871/91729347-b7db7c00-eba4-11ea-90d7-2b365c561e30.gif)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Safari
 - Version 13.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bswinnerton** [comment]
Hey @schiederme, thanks for reporting this. I shipped a new frontend today that should have this bug fixed. If it's not, please let me know and we can reopen this.
