### ISSUE TITLE
Support MikroTik RouterOS CHR

### ISSUE THREAD

**Issue by Mehrikk** [neptune-networks/feedback#39]
Our network infrastructure is based on RouterOS (MikroTik routers and RouterOS CHR VMs).
We would not want to use other lInux distributions for our infrastructure.
We tried to run live-cd linux (ubuntu, debian and centos) and write a raw RouterOS CHR image to storage, but every time we got a UEFI error.
Can you add the ability to install RouterOS from a billing system or help deploy a raw routeros image for us on your platform?

**Comment by bswinnerton** [comment]
Hi @Mehrikk, to the best of my knowledge RouterOS doesn't support UEFI (though the `7.x` beta version does). Neptune's VMs use UEFI by default, which is likely the source of the problem.

I'll work on a more permanent fix for others who also wish to use RouterOS, but in the mean time please email support@neptunenetworks.org with the email address on your account and I can set up a non-UEFI VM for you with the CHR image.

**Comment by bswinnerton** [comment]
Hi @Mehrikk, I've added Mikrotik 6.47.7 to the list of distributions when [creating a new virtual machine](https://app.neptunenetworks.org/virtual_machines/new/). I'd recommend destroying the old VM and creating a new one with this option.

Let me know if you have any problems or need a different version. Going to optimistically close this out.

**Comment by Mehrikk** [comment]
Hi @bswinnerton. 
I have no words. It's great!
I'm glad I offered my boss your service to host our VM.
Thank you for the revision.

I am sorry for the long response time. I'm in a different time zone.
