### ISSUE TITLE
BGP Session

### ISSUE THREAD

**Issue by Dimitrifsc** [neptune-networks/feedback#40]
Hello,
I have a problem connecting to the BGP session.
Here is the error:
`  BGP state:          Active
    Neighbor address: 23.157.160.161
    Neighbor AS:      21700
    Connect delay:    5/5
    Last error:       Socket: Connection reset by peer
`
The bird configuration : 
`protocol bgp neptunenetworks
{
    local as 207320;
    source address 23.157.160.183;
    import none;
    export all;
    graceful restart on;
    neighbor 23.157.160.161 as 21700;
}
`

The email of my account is : contact@gmyserv.com .
Thanks you in advance.

**Comment by bswinnerton** [comment]
Hi @Dimitrifsc,

I just checked and it looks like the IPv4 session is established. BGP configurations are rolled out using scheduled jobs, so there can sometimes be a delay between when the VM is created and when the BGP session becomes established, which I think is what you ran into here.

I'm going to close this out, but please feel free to let me know if you're still having any problems. You can also always reach out to support@neptunenetworks.org.
