### ISSUE TITLE
Source IP Filtering?  How do I not use Cogent?

### ISSUE THREAD

**Issue by firstkevinds** [neptune-networks/feedback#42]
Does Neptune Networks filter source IPs?  Having an odd issue when using a VPN connections with 'use-default-route'..  Wondering if source-IP-filtering could be the cause.

Secondly, and this is probably a 'silly' question, how do I use BGP to prevent Cogent from being used upstream?

**Comment by bswinnerton** [comment]
👋 Hi @online-stuff,

> Does Neptune Networks filter source IPs? Having an odd issue when using a VPN connections with 'use-default-route'.. Wondering if source-IP-filtering could be the cause.

Neptune does filter source IPs. For IPv4, the only allowed address is the one assigned to your virtual machine. For IPv6, any address in the /64 is allowed. We do this to prevent address spoofing on the platform.

> Secondly, and this is probably a 'silly' question, how do I use BGP to prevent Cogent from being used upstream?

You can do this using the BGP communities listed on our [Peering Page](https://neptunenetworks.org/peering). Specifically for Cogent, you should be able to tag your announced prefixes with `21700:666:174` to prevent the prefixes from being announced to them.
