### ISSUE TITLE
Bad IPv6 Gateway

### ISSUE THREAD

**Issue by JamCh01** [neptune-networks/feedback#45]
**Describe the bug**

**To Reproduce**
1. Go to 'virtual_machines panel'
2. Click on 'virtual machines '
3. Scroll down to 'emmm, nothing'
4. See error-> bad IPv6 gateway

**Expected behavior**

**Screenshots**
[![IYKHgI.png](https://z3.ax1x.com/2021/11/09/IYKHgI.png)](https://imgtu.com/i/IYKHgI)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6.1
 - Browser chrome
 - Version 95.0.4638.69

**Additional context**
as you can see My IPv6 address is 2602:fe2e:3:d5:e9:c4ff:fe88:9540/64, but gateway address is fe80::216:3eff:fe5f:91d

**Comment by bswinnerton** [comment]
Hi @JamCh01, that is a link local address and it is intentionally not in your /64 address space. You should be able to ping that address and use it as your gateway in all VMs that we support.

**Comment by bswinnerton** [comment]
If you'd like help debugging, feel free to email support@neptunenetworks.org.
