### ISSUE TITLE
reverse dns has been broken for a while

### ISSUE THREAD

**Issue by dave4445** [neptune-networks/feedback#46]
**Describe the bug**

$ host 23.157.160.161
Host 161.160.157.23.in-addr.arpa not found: 2(SERVFAIL)
$ 

Dec 27 16:26:04 ganges named[24400]: REFUSED unexpected RCODE resolving '161.160.157.23.in-addr.arpa/PTR/IN': 2a06:98c1:50::ac40:21bb#53
Dec 27 16:26:04 ganges named[24400]: REFUSED unexpected RCODE resolving '161.160.157.23.in-addr.arpa/PTR/IN': 2606:4700:50::adf5:3ae2#53
Dec 27 16:26:04 ganges named[24400]: REFUSED unexpected RCODE resolving '161.160.157.23.in-addr.arpa/PTR/IN': 2606:4700:58::adf5:3bbb#53
Dec 27 16:26:04 ganges named[24400]: REFUSED unexpected RCODE resolving '161.160.157.23.in-addr.arpa/PTR/IN': 2a06:98c1:50::ac40:20e2#53
Dec 27 16:26:04 ganges named[24400]: REFUSED unexpected RCODE resolving '161.160.157.23.in-addr.arpa/PTR/IN': 2803:f800:50::6ca2:c1bb#53
Dec 27 16:26:04 ganges named[24400]: REFUSED unexpected RCODE resolving '161.160.157.23.in-addr.arpa/PTR/IN': 2803:f800:50::6ca2:c0e2#53
Dec 27 16:26:04 ganges named[24400]: REFUSED unexpected RCODE resolving '161.160.157.23.in-addr.arpa/PTR/IN': 172.64.33.187#53
Dec 27 16:26:04 ganges named[24400]: REFUSED unexpected RCODE resolving '161.160.157.23.in-addr.arpa/PTR/IN': 173.245.58.226#53
Dec 27 16:26:04 ganges named[24400]: REFUSED unexpected RCODE resolving '161.160.157.23.in-addr.arpa/PTR/IN': 108.162.193.187#53
Dec 27 16:26:04 ganges named[24400]: REFUSED unexpected RCODE resolving '161.160.157.23.in-addr.arpa/PTR/IN': 108.162.192.226#53
Dec 27 16:26:04 ganges named[24400]: REFUSED unexpected RCODE resolving '161.160.157.23.in-addr.arpa/PTR/IN': 173.245.59.187#53
Dec 27 16:26:05 ganges named[24400]: REFUSED unexpected RCODE resolving '161.160.157.23.in-addr.arpa/PTR/IN': 172.64.32.226#53

**Comment by bswinnerton** [comment]
Thanks @dave4445, looking into this now.

**Comment by dave4445** [comment]
resolved
