### ISSUE TITLE
Website SSL error https://neptunenetworks.org/

### ISSUE THREAD

**Issue by SimonSchmitz** [neptune-networks/feedback#47]
**Describe the bug**
Website SSL error https://neptunenetworks.org/
**To Reproduce**
1. Go to 'https://neptunenetworks.org/'
2. See error

**Comment by bswinnerton** [comment]
Thank you for the report, @SimonSchmitz. It appears there was an issue with GitHub Pages requesting an SSL certificate from Let's Encrypt. This should now be resolved, but let me know if you run into any problems.
